### ISSUE TITLE
Update to bolt v2

### ISSUE THREAD

**Issue by Vivalldi** [seratch/slack-app-examples#17]
Are there any plans to update this repo to reflect the changes introduced in bolt v2?

Or will we just refer to https://github.com/slackapi/bolt/issues/220 once that is in place?

**Comment by seratch** [comment]
If you're looking for information about v2 migration, https://slack.dev/bolt/tutorial/migration-v2 is the best resource to learn how to do it. Of course, I can work on upgrading the examples in this repository when I have a chance!

**Comment by Vivalldi** [comment]
I should have noted this earlier, but the reason I was asking is I'm trying to get my current bolt app setup on FaaS. I've checked every issue regarding async handlers I could find to no avail.

I'll submit a PR to the serverless examples if I figure something out

**Comment by seratch** [comment]
I see. It would be greatly appreciated if you could send PRs. I've updated another sample with FaaS compatible settings - https://github.com/seratch/bolt-starter/blob/9a2d8a7888e94d926db9db2dbefd449478ab8ce1/index.js#L13-L15

**Comment by Vivalldi** [comment]
Interestingly enough, I've peeked at all of your different repos (which have been more than helpful 😄) and have attempted to implement the various FaaS examples.  I'll be more than happy to update once I'm confident I've got something working.

My current setup looks like

`app.js`
```js
const { App, ExpressReceiver, LogLevel } = require("@slack/bolt");

const expressReceiver = new ExpressReceiver({
  signingSecret: process.env.SLACK_SIGNING_SECRET,
});

const app = new App({
  token: process.env.SLACK_BOT_TOKEN,
  receiver: expressReceiver,
  logLevel: LogLevel.DEBUG,
  processBeforeResponse: false,
});

const eventHandlers = require("./events.js");

app.shortcut("shortcut_question", eventHandlers.shortcutQuestion);
// ... More handlers, just showcasing the one for now

module.exports.expressReceiver = expressReceiver;
```

`handler.js`
```js
"use strict";

const { expressReceiver } = require("./src/app");
const awsServerlessExpress = require("aws-serverless-express");
const server = awsServerlessExpress.createServer(expressReceiver.app);

module.exports.app = (event, context) => {
  awsServerlessExpress.proxy(server, event, context, "PROMISE").promise;
};
```

`shortcutQuestion` is an async function that has a somewhat long runtime in that it first downloads a file, saves some info to dynamo db, then opens a view and notes the view id. In psuedo code it looks like
```js
const shortcutQuestion = async ({ ack, client, context, shortcut }) => {
  await ack();
  console.info("[INFO] Start (λ: `shortcutQuestion`)");

  // get and save data
  const data = await getDatafileForMessage();
  await saveDataToDB(data);

  // open view
  await client.views.open({
    token: context.botToken,
    trigger_id: shortcut.trigger_id,
    view: {...},
  });
  console.info("[INFO] End (λ: `shortcutQuestion`)");
}
```

If I run using the setup above everything runs fine, with the exception that the lambda never terminates (note lack of lambda `RequestID` & `Billed Duration` output)
```shell
offline: POST /dev/slack/events (λ: kue)
[DEBUG]  WebClient:0 initialized
[DEBUG]  WebClient:0 apiCall('auth.test') start
[DEBUG]  WebClient:0 will perform http request
[DEBUG]  WebClient:0 http response received
[DEBUG]  WebClient:1 initialized
[DEBUG]  bolt-app Conversation context failed loading for ID: C011GNRPS8P, error: Conversation not found
[INFO] Start (λ: `shortcutQuestion`)
[DEBUG]  WebClient:1 apiCall('views.open') start
[DEBUG]  WebClient:1 will perform http request
[DEBUG]  WebClient:1 http response received
[INFO] End (λ: `shortcutQuestion`)
```

If I change the handler to be
```js
module.exports.app = (event, context, callback) => {
  awsServerlessExpress.proxy(server, event, context, "CALLBACK", callback);
};
```

The lambda _does_ complete, however, it completes before `shortcutQuestion` has finished. (note lack of ``[INFO] End (λ: `shortcutQuestion`)``)
```shell
offline: POST /dev/slack/events (λ: kue)
[DEBUG]  WebClient:0 initialized
[DEBUG]  WebClient:0 apiCall('auth.test') start
[DEBUG]  WebClient:0 will perform http request
[DEBUG]  WebClient:0 http response received
[DEBUG]  WebClient:1 initialized
[DEBUG]  bolt-app Conversation context failed loading for ID: C011GNRPS8P, error: Conversation not found
[INFO] Start (λ: `shortcutQuestion`)
offline: (λ: kue) RequestId: ck9ecuhik0002iio1bq62btv1  Duration: 254.10 ms  Billed Duration: 300 ms
```

**Comment by seratch** [comment]
processBeforeResponse needs to be true for both App and Receiver.

**Comment by seratch** [comment]
Also, be noted that if a listener requires 3+ seconds to respond, bolt v2 isn't free from timeout errors. In such cases, you need to have a queue (say, Amazon SQS) to run some operations asynchronously.

**Comment by Vivalldi** [comment]
Ahh okay. I feel like a goof. I'll restructure to offload those tasks (as the `processBeforeResponse` in both `app` and `receiver` didn't change the output for both handler styles). I Will let you know when I've got a PR. Thanks for the quick responses.

**Comment by seratch** [comment]
I have updated all Bolt samples to use v2.
